### ISSUE TITLE
multiple images

### ISSUE THREAD

**Issue by anthonynasr** [funkensturm/ember-cli-file-picker#61]
i can't get data for multiple images ..i just have the number of files and their names..i need the data to upload it into rails

**Comment by mireille1** [comment]
i have the same problem ..please i need a solution

**Comment by fsmanuel** [comment]
@anthonynasr @mireille1 How do you think that should work. We need some specs for it.

It is possible right now to have an action `filesLoaded`. The payload are the files and you can use `readFile` ([docs](https://github.com/funkensturm/ember-cli-file-picker/blob/master/addon/lib/helpers.js#L18)) to get them in the desired format.

```js
import { readFile } from 'ember-cli-file-picker/lib/helpers';

actions: {
  filesLoaded(files) {
    // map over the files and use readFile to get all the promises
    // use RSVP.all to do what ever you want *
  }
}
```
\* [RSVP.all](https://github.com/tildeio/rsvp.js/#arrays-of-promises)

I haven't implemented the feature yet because I didn't had the need to. With the current version the previews don't work for multiple files. If you send a PR I'm happy to merge and implement the right behavior for `filesLoaded` as described above.

**Comment by fsmanuel** [comment]
@anthonynasr @mireille1 did this work or do we have to implement something?

**Comment by anthonynasr** [comment]
heyy
it works now i've found a new solution .. addon now is removed i use jquery
for multiple upload and for the backend part i still use carrierwave with
some changes
thank you for asking
have a nice day

**Comment by mireille1** [comment]
Hello,
As anthony said ,
We really appreciate
Thank you,
